import { Linking, Share } from 'react-native';
import type { AdherenceSummary, DayCell } from './reportHelpers';

interface ReportInput {
  patientName: string;
  monthLabel: string;
  summary: AdherenceSummary;
  cells: DayCell[];
}

const STATUS_LABEL: Record<DayCell['status'], string> = {
  allTaken: 'OK',
  partial: 'Partial',
  missed: 'Missed',
  pending: 'Pending',
  none: '-',
};

/**
 * Build a plain-text adherence report. We deliberately avoid expo-print /
 * expo-sharing here because their Android Gradle plugins (`expo-module-
 * gradle-plugin`) require a fully-prebuilt Expo Modules autolinking setup,
 * which isn't always present when the user builds the bare android/ folder
 * directly. The system share sheet (React Native core `Share.share`) and
 * `Linking.openURL` both ship with React Native and need no native config.
 */
function buildSummaryText({
  patientName,
  monthLabel,
  summary,
}: ReportInput): string {
  const lines = [
    'MediReminder India - Adherence Report',
    `Patient: ${patientName}`,
    `Period: ${monthLabel} (last ${summary.windowDays} days)`,
    '',
    `Adherence: ${summary.adherencePct}%`,
    `Current streak: ${summary.currentStreakDays} day(s)`,
    `Doses taken: ${summary.takenDoses} / ${summary.totalDoses}`,
    `Missed: ${summary.missedDoses}`,
    `Skipped: ${summary.skippedDoses}`,
    `Pending: ${summary.pendingDoses}`,
  ];
  if (summary.bestDay) lines.push(`Best day: ${summary.bestDay}`);
  if (summary.worstDay && summary.worstDay !== summary.bestDay) {
    lines.push(`Needs attention: ${summary.worstDay}`);
  }
  lines.push('', 'Generated by MediReminder India.');
  return lines.join('\n');
}

function buildDetailedText(input: ReportInput): string {
  const head = buildSummaryText(input);
  const inMonth = input.cells.filter((c) => c.inMonth && c.total > 0);
  if (inMonth.length === 0) return head;
  const days = inMonth
    .map((c) => `  ${c.date}  ${STATUS_LABEL[c.status]}  ${c.taken}/${c.total}`)
    .join('\n');
  return `${head}\n\nDaily breakdown:\n${days}`;
}

/**
 * Open the system share sheet so the user can pick any destination
 * (Gmail, Drive, WhatsApp, Telegram, Files, etc.) for the summary.
 */
export async function generateAndSharePdf(input: ReportInput): Promise<void> {
  const message = buildDetailedText(input);
  await Share.share({
    title: 'MediReminder Report',
    message,
  });
}

/**
 * Direct WhatsApp deep-link with a short summary.
 *
 * Why we don't use Linking.canOpenURL():
 *   On Android 11+ (API 30+) `canOpenURL("whatsapp://...")` returns false
 *   unless the app declares the `whatsapp` SCHEME in its <queries>. Just
 *   listing the WhatsApp package isn't enough - scheme-visibility and
 *   package-visibility are filtered independently. So users with
 *   WhatsApp installed were getting the "not installed" fallback.
 *
 * Strategy:
 *   1. Try the native `whatsapp://` scheme via openURL directly. This
 *      either launches WhatsApp instantly or throws.
 *   2. If it throws, fall back to the universal `https://wa.me/?text=...`
 *      link. Android always allows querying https URLs, and Android's
 *      app-link handler will route this to WhatsApp if installed - or
 *      to the browser (which then offers to open it in WhatsApp) if not.
 *   3. Only return false when BOTH fail (extremely rare).
 */
export async function shareViaWhatsApp(input: ReportInput): Promise<boolean> {
  const text = buildSummaryText(input);
  const encoded = encodeURIComponent(text);
  const nativeUrl = `whatsapp://send?text=${encoded}`;
  const webUrl = `https://wa.me/?text=${encoded}`;

  try {
    await Linking.openURL(nativeUrl);
    return true;
  } catch {
    // Native scheme blocked or app not installed - try the https handoff.
    try {
      await Linking.openURL(webUrl);
      return true;
    } catch {
      return false;
    }
  }
}
